[build]
  command = "npm ci"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/gerar-pdf"
  to = "/.netlify/functions/api/gerar-pdf"
  status = 200
  force = true
  methods = ["POST"]

[functions]
  node_bundler = "esbuild"